[platformio]
workspace_dir = .pio.nosync

default_envs = cyd_ili9341

[env]
platform = espressif32 @ ^6.12.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_unflags =
  -Os
build_flags =
  -O2
  -D LV_CONF_INCLUDE_SIMPLE
  -D USER_SETUP_LOADED
  -D ST7789_DRIVER=0
  -I include
lib_deps =
  lvgl/lvgl @ 8.3.11
  lovyan03/LovyanGFX @ ^1.2.7
  bodmer/TFT_eSPI @ ^2.5.43
  sensirion/Sensirion I2C SEN66 @ ^1.0.0
  tzapu/WiFiManager @ ^2.0.17
  knolleary/PubSubClient @ ^2.8

[env:cyd_ili9341]
board = esp32dev
board_build.partitions = huge_app.csv
build_flags =
  ${env.build_flags}
  -D CYD_I2C_SDA_PIN=27
  -D CYD_I2C_SCL_PIN=22
  -D CYD_VARIANT_ILI9341=1
  -D CYD_LCD_RGB_ORDER=1
  -D CYD_LCD_ROTATION=4
  -D CYD_LCD_PANEL_WIDTH=320
  -D CYD_LCD_PANEL_HEIGHT=240
  -D UPDATE_INTERVAL=5000
;  -D SIMULATION=0 ; 0=false, 1=true

[env:ili9341_r4]
board = esp32dev
build_flags =
  ${env.build_flags}
  -D CYD_VARIANT_ILI9341=1
  -D TEST_DISPLAY=1
  -D CYD_LCD_RGB_ORDER=1
  -D CYD_LCD_ROTATION=4
  -D CYD_LCD_PANEL_WIDTH=320
  -D CYD_LCD_PANEL_HEIGHT=240
